/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CloneRewarderTime } from "./CloneRewarderTime";
export type { IMasterChefV2 } from "./IMasterChefV2";
