/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface SushiMakerKashiInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "claimOwnership"
      | "convert"
      | "convertMultiple"
      | "owner"
      | "pendingOwner"
      | "setBridge"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "LogBridgeSet"
      | "LogConvert"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "claimOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "convert",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "convertMultiple",
    values: [AddressLike[]]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingOwner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setBridge",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike, boolean, boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "claimOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "convert", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "convertMultiple",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setBridge", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace LogBridgeSetEvent {
  export type InputTuple = [token: AddressLike, bridge: AddressLike];
  export type OutputTuple = [token: string, bridge: string];
  export interface OutputObject {
    token: string;
    bridge: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LogConvertEvent {
  export type InputTuple = [
    server: AddressLike,
    token0: AddressLike,
    amount0: BigNumberish,
    amountBENTO: BigNumberish,
    amountSUSHI: BigNumberish
  ];
  export type OutputTuple = [
    server: string,
    token0: string,
    amount0: bigint,
    amountBENTO: bigint,
    amountSUSHI: bigint
  ];
  export interface OutputObject {
    server: string;
    token0: string;
    amount0: bigint;
    amountBENTO: bigint;
    amountSUSHI: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SushiMakerKashi extends BaseContract {
  connect(runner?: ContractRunner | null): SushiMakerKashi;
  waitForDeployment(): Promise<this>;

  interface: SushiMakerKashiInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  claimOwnership: TypedContractMethod<[], [void], "nonpayable">;

  convert: TypedContractMethod<[kashiPair: AddressLike], [void], "nonpayable">;

  convertMultiple: TypedContractMethod<
    [kashiPair: AddressLike[]],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pendingOwner: TypedContractMethod<[], [string], "view">;

  setBridge: TypedContractMethod<
    [token: AddressLike, bridge: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike, direct: boolean, renounce: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "claimOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "convert"
  ): TypedContractMethod<[kashiPair: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "convertMultiple"
  ): TypedContractMethod<[kashiPair: AddressLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pendingOwner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setBridge"
  ): TypedContractMethod<
    [token: AddressLike, bridge: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<
    [newOwner: AddressLike, direct: boolean, renounce: boolean],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "LogBridgeSet"
  ): TypedContractEvent<
    LogBridgeSetEvent.InputTuple,
    LogBridgeSetEvent.OutputTuple,
    LogBridgeSetEvent.OutputObject
  >;
  getEvent(
    key: "LogConvert"
  ): TypedContractEvent<
    LogConvertEvent.InputTuple,
    LogConvertEvent.OutputTuple,
    LogConvertEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "LogBridgeSet(address,address)": TypedContractEvent<
      LogBridgeSetEvent.InputTuple,
      LogBridgeSetEvent.OutputTuple,
      LogBridgeSetEvent.OutputObject
    >;
    LogBridgeSet: TypedContractEvent<
      LogBridgeSetEvent.InputTuple,
      LogBridgeSetEvent.OutputTuple,
      LogBridgeSetEvent.OutputObject
    >;

    "LogConvert(address,address,uint256,uint256,uint256)": TypedContractEvent<
      LogConvertEvent.InputTuple,
      LogConvertEvent.OutputTuple,
      LogConvertEvent.OutputObject
    >;
    LogConvert: TypedContractEvent<
      LogConvertEvent.InputTuple,
      LogConvertEvent.OutputTuple,
      LogConvertEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
